const menu_data = [
    // 빵
    [
        { menu: "크로와상샌드위치", src: './img/menu/bread-tab02-11.png', content: "고메버터의 풍미가 은은하게 퍼지는 크로와상빵에 신선한 채소가 들어간 샌드위치", kal: 398, sugars: 3.01, protein: 12.56, saturated_fat: 5.249, natrium: 586 },
        { menu: "치킨페스츄리샌드위치", src: './img/menu/bread-tab02-10.png', content: "페스츄리빵에 담백한 닭가슴살과 신선한 채소가 들어간 샌드위치", kal: 570, sugars: 5.22, protein: 27.35, saturated_fat: 6.36, natrium: 677 },
        { menu: "치킨샐러", src: './img/menu/bread-tab02-09.png', content: "담백한 닭가슴살과 신선한 채소가 들어간 치킨샐러드", kal: 110, sugars: 3, protein: 10, saturated_fat: 1.5, natrium: 270 },
        { menu: "잡곡베이글샌드위치", src: './img/menu/bread-tab02-08.png', content: "고소하고 바삭한 잡곡 베이글빵에 크림치즈와 신선찬 야채가 가득 들어있는 샌드위치" , kal: 230, sugars: 6, protein: 9, saturated_fat: 0.5, natrium: 480},
        { menu: "식빵러스크", src: './img/menu/bread-tab02-06.png', content: "수분함량이 적어 소화가 잘되고 빵카페에서 직접 구워 만들어 담백하고 바삭한 러스크" , kal: 151, sugars: 2, protein: 3, saturated_fat: 4.5, natrium: 210},
        { menu: "갈릭크림치즈바게트", src: './img/menu/bread-tab01-01.png', content: "향긋한 마늘과 달콤한 크림치즈가 어우러진 마늘바케트" , kal: 330, sugars: 13, protein: 6, saturated_fat: 9, natrium: 339},
        { menu: "감자볼케이노", src: './img/menu/bread-tab01-02.png', content: "감자샐러드가 가득 들어간 부드럽고 담백한 감자빵" , kal: 177, sugars: 5, protein: 4, saturated_fat: 0.5, natrium: 216},
        { menu: "고로케", src: './img/menu/bread-tab01-03.png', content: "감자와 야채가 가득 들어간 바삭한 옛날식 고로케" , kal: 320, sugars: 13, protein: 4, saturated_fat: 7, natrium: 420},
        { menu: "곡물식빵", src: './img/menu/bread-tab01-05.png', content: "탕종반죽을 이용해 더욱 쫄깃하고 고소한 곡물 식빵" , kal: 143, sugars: 3, protein: 5, saturated_fat: 1.5, natrium: 230},
        { menu: "공주밤빵", src: './img/menu/bread-tab01-06.png', content: "국산 토종 밤이 가득 들어간 쫄깃하고 달콤한 밤 빵" , kal: 175, sugars: 7, protein: 5, saturated_fat: 2, natrium: 280},
        { menu: "나가사키카스텔라", src: './img/menu/bread-tab01-08.png', content: "부드럽고 달콤한 빵카페만의 고급 카스텔라" , kal: 297, sugars: 29, protein: 8, saturated_fat: 4, natrium: 65},
        { menu: "레몬마들렌", src: './img/menu/bread-tab01-15.png', content: "향긋한 레몬향이 퍼지는 달콤하고 상큼한 마들렌" , kal: 82, sugars: 0, protein: 1.84, saturated_fat: 1, natrium: 0},
        { menu: "매콤피자소세지빵", src: './img/menu/bread-tab01-17.png', content: "맛있게 매콤한 피자맛을 기본으로한 소세지빵" , kal: 345, sugars: 8, protein: 8, saturated_fat: 6, natrium: 530},
        { menu: "메이플크림치즈빵", src: './img/menu/bread-tab01-20.png', content: "천연재료로 만든 달콤한 메이플시럽과 크림치즈가 어우러진 빵" , kal: 194, sugars: 7, protein: 5, saturated_fat: 3.1, natrium: 226},
        { menu: "모닝빵", src: './img/menu/bread-tab01-21.png', content: "담백하고 부드러운 가장 기본적인 모닝빵" , kal: 235, sugars: 10, protein: 6, saturated_fat: 4.5, natrium: 220},
        { menu: "모카빵", src: './img/menu/bread-tab01-22.png', content: "바삭하고 향기로운 모카 비스켓과 달콤한 춘설앙금이 어우러진 빵" , kal: 215, sugars: 13, protein: 4, saturated_fat: 2, natrium: 220},
        { menu: "몽블랑", src: './img/menu/bread-tab01-23.png', content: "겉은 바삭, 속은 촉촉한 버터함유량이 높아 고소한 맛과 깊은 풍미가 특징인 빵결이 살아있는 페스츄리 빵" , kal: 369, sugars: 13, protein: 6, saturated_fat: 12.85, natrium: 365.8},
        { menu: "미니딸기파이", src: './img/menu/bread-tab01-24.png', content: "딸기 마시멜로우가 들어간 딸기 초코파이" , kal: 154, sugars: 12, protein: 2, saturated_fat: 3.8, natrium: 80},
        { menu: "미니만주", src: './img/menu/bread-tab01-25.png', content: "직접 끓여만든 팥이 가득 들어있어서 달지않고 고소한 미니만주" , kal: 155, sugars: 7, protein: 4, saturated_fat: 0.6, natrium: 60},
        { menu: "미니초코파이", src: './img/menu/bread-tab01-26.png', content: "달콤한 마시멜로우가 들어간 초코파이", kal: 154, sugars: 12, protein: 2, saturated_fat: 3.8, natrium: 80 },
        { menu: "밤팥빵", src: './img/menu/bread-tab01-27.png', content: "직접 끓여 달지않고, 국산 알밤이 통으로 들어간 밤팥빵" , kal: 200, sugars: 15, protein: 5, saturated_fat: 2.1, natrium: 160},
        { menu: "어니언바질베이글", src: './img/menu/bread-tab01-36.png', content: "양파와 바질의 풍미가 가득한 빵카페만의 차갑게 먹는 특별한 베이글" , kal: 330, sugars: 9, protein: 11, saturated_fat: 0.6, natrium: 450},
        { menu: "버터프레첼", src: './img/menu/bread-tab01-29.png', content: "최고급 고메버터의 풍미가 가득한 프레첼" , kal: 505, sugars: 9, protein: 10, saturated_fat: 12, natrium: 600},
        { menu: "베이컨갈릭", src: './img/menu/bread-tab01-30.png', content: "향긋한 마늘소스에 베이컨과 크림치즈의 풍미가 어우러진 베이컨갈릭빵" , kal: 330, sugars: 13 , protein: 6, saturated_fat: 9, natrium: 339},
        { menu: "빵선생식빵", src: './img/menu/bread-tab01-31.png', content: "빵카페만의 부드럽고 담백한 식빵" , kal: 169, sugars: 2, protein: 6, saturated_fat: 3.3, natrium: 287},
        { menu: "빵카스테라", src: './img/menu/bread-tab01-32.png', content: "부드러운 식감에 각종 견과류가 들어가 고소하고 촉촉한 빵 카스텔라" , kal: 255, sugars: 21, protein: 6, saturated_fat: 3, natrium: 65},
        { menu: "생크림크로와상", src: './img/menu/bread-tab01-33.png', content: "향긋한 딸기향이 가득한 달콤한 크로와상" , kal: 104, sugars: 5, protein: 3, saturated_fat: 5, natrium: 178},
        { menu: "앙버터", src: './img/menu/bread-tab01-35.png', content: "직접끓여 달지 않은 팥에 최고급 버터를 이용한 빵카페만의 앙버터" , kal: 674, sugars: 3.17, protein: 15.97, saturated_fat: 16.318, natrium: 719},
        { menu: "에그타르트", src: './img/menu/bread-tab01-37.png', content: "부드러운 커스터드 크림과 고소한 페이스트리가 어우러진 에그타르트" , kal: 135, sugars: 5, protein: 2, saturated_fat: 4, natrium: 110},
        { menu: "옥수수식빵", src: './img/menu/bread-tab01-38.png', content: "탕종반죽을 이용해 더욱 쫄깃하고 고소한 옥수수 식빵" , kal: 275, sugars: 6, protein: 9, saturated_fat: 2, natrium: 480},
        { menu: "올리브치아바타", src: './img/menu/bread-tab01-39.png', content: "저온에서 숙성 발효시킨 건강한 치아바타 빵" , kal: 378, sugars: 7, protein: 20, saturated_fat: 4.8, natrium: 793},
        { menu: "우유식빵", src: './img/menu/bread-tab01-41.png', content: "탕종반죽을 이용해 더욱 쫄깃하고 고소한 우유 식빵" , kal: 220, sugars: 5, protein: 7, saturated_fat: 2, natrium: 330},
        { menu: "유러피안소세지빵", src: './img/menu/bread-tab01-42.png', content: "베사멜소스로 만든 담백한 조리빵" , kal: 345, sugars: 8, protein: 8, saturated_fat: 6, natrium: 530},
        { menu: "유자크림치즈빵", src: './img/menu/bread-tab01-43.png', content: "상큼한 유자와 달콤한 크림치즈가 어우러진 빵카페만의 유자크림치즈빵" , kal: 194, sugars: 7, protein: 5, saturated_fat: 3.1, natrium: 226},
        { menu: "제노와즈", src: './img/menu/bread-tab01-44.png', content: "촉촉하고 부드러운 카스테라빵" , kal: 355, sugars: 37, protein: 9, saturated_fat: 2.1, natrium: 75},
        { menu: "찹쌀바게트", src: './img/menu/bread-tab01-45.png', content: "각종 곡물과 쫄깃한 찹쌀이 들어가 더욱 고소한 바게트빵" , kal: 286, sugars: 4.23, protein: 9.64, saturated_fat: 2.36, natrium: 294.76},
        { menu: "초코스콘", src: './img/menu/bread-tab01-46.png', content: "달지않아 간식으로 좋은 빵카페 스콘" , kal: 195, sugars: 7, protein: 3, saturated_fat: 6, natrium: 85},
        { menu: "초코타르트", src: './img/menu/bread-tab01-48.png', content: "바삭한 타르트에 쫀득하고 진한 가나슈초코 필링이 가득들어있는 초코타르트" , kal: 160, sugars: 7, protein: 2, saturated_fat: 7, natrium: 100},
        { menu: "츄러스링", src: './img/menu/bread-tab01-49.png', content: "크림치즈베이스에 시나몬향이 은은하게 퍼지는 츄러스" , kal: 100, sugars: 4, protein: 1, saturated_fat: 1.4, natrium: 115},
        { menu: "치즈납작이", src: './img/menu/bread-tab01-50.png', content: "쿡살라미, 크림치즈, 건조토마토가 들어간 납작한 치즈빵" , kal: 230, sugars: 7, protein: 5, saturated_fat: 7, natrium: 300},
        { menu: "치즈풍덩", src: './img/menu/bread-tab01-51.png', content: "쫀득하고 고소한 치즈볼빵" , kal: 143, sugars: 2, protein: 6, saturated_fat: 1, natrium: 345},
        { menu: "크로와상", src: './img/menu/bread-tab01-54.png', content: "최고급 고메버터의 풍미가 은은하게 퍼지는 바삭하고 담백한 크로와상" , kal: 231.00, sugars: 6.42, protein: 4.67, saturated_fat: 6.65, natrium: 424.00},
        { menu: "페스츄리피자", src: './img/menu/bread-tab01-55.png', content: "겹겹이 쌓여 바삭하고 부드러운 두툼한 페스츄리 도우에 각종 토핑이 듬뿍 올라간 피자" , kal: 256.00, sugars: 3.38, protein: 11.47, saturated_fat: 4.28, natrium: 511.00},
        { menu: "페퍼소세지", src: './img/menu/bread-tab01-56.png', content: "육즙이 살아있는 페퍼소시지에 양파의 씹는맛이 더해진 소시지빵" , kal: 345, sugars: 8.00, protein: 8.00, saturated_fat: 6.00, natrium: 530.00},
        { menu: "피칸파이", src: './img/menu/bread-tab01-57.png', content: "달콤하고 바삭한 피칸파이", kal: 659.00, sugars: 5.00, protein: 18.00, saturated_fat: 59.00, natrium: 0.00}

    ],
    // 케이크(홀,롤)
    [
        { menu: "계절과일타르트(딸기)", src: './img/menu/untitled19.png', content: "두꺼운 크림치즈에 딸기가 가득올라간 타르트케이크", kal: 1795, sugars: 121, protein: 29, saturated_fat: 51, natrium: 430 },
        { menu: "계절과일타르트(청포도)", src: './img/menu/untitled18.png', content: "두꺼운 크림치즈에 딸기가 가득올라간 타르트케이크", kal: 1795, sugars: 121, protein: 29, saturated_fat: 51, natrium: 430 },
        { menu: "과일생크림케이크(딸기)", src: './img/menu/untitled17.png', content: "동물성 생크림을 사용해 더욱 건강한 딸기 생크림 케이크", kal: 170, sugars: 8, protein: 2.2, saturated_fat: 6, natrium: 45 },
        { menu: "딸기롤케이크", src: './img/menu/untitled16.png', content: "향긋한 딸기와 생크림 카스텔라가 어우러진 롤케이크", kal: 320, sugars: 31, protein: 9, saturated_fat: 6, natrium: 80 },
        { menu: "블루베리쉬폰케이크", src: './img/menu/untitled12.png', content: "블루베리 쉬폰베이스를 이용한 제품으로 폭신한 쉬폰케이크에 블루베리의 상큼한 맛이 특징", kal: 348, sugars: 4.1, protein: 14, saturated_fat: 37, natrium: 0 },
        { menu: "생크림롤케이크", src: './img/menu/untitled11.png', content: "가끔 달달한 디저트가 땡길 때, 부담 없이 먹고 싶은 부드럽고 달콤한 생크림 롤케이크", kal: 320, sugars: 31, protein: 9, saturated_fat: 6, natrium: 80 },
        { menu: "쇼콜라클래식", src: './img/menu/untitled9.png', content: "바닐라크림과 진한 초콜릿 카스텔라", kal: 270, sugars: 21, protein: 3, saturated_fat: 7, natrium: 65 },
        { menu: "쌀쉬폰", src: './img/menu/untitled8.png', content: "쌀가루로 만들어 부드럽고 담백한 쉬폰", kal: 240, sugars: 23, protein: 9, saturated_fat: 0.9, natrium: 190 },
        { menu: "초코생크림케이크", src: './img/menu/untitled6.png', content: "건강한 동물성 생크림에 달콤한 가나슈크림이 더해져 부드럽고 달콤한 초코생크림 케이크", kal: 287, sugars: 16, protein: 4, saturated_fat: 4.2, natrium: 196 },
        { menu: "초코쉬폰케이크", src: './img/menu/untitled5.png', content: "초코 쉬폰베이스를 이용한 제품으로 폭신한 쉬폰케이크에 가나슈의 달콤한 맛이 특징", kal: 195, sugars: 16, protein: 3, saturated_fat: 6, natrium: 120 },
        { menu: "키리쉬롤케이크", src: './img/menu/untitled4.png', content: "겹겹이 쌓은 초콜릿 쉬폰케이크 층 사이를 생크림과 체리로 채운 독일을 정통 조각 케이크", kal: 305, sugars: 26.31, protein: 5.29, saturated_fat: 6.234, natrium: 116 },
        { menu: "키리쉬케이크", src: './img/menu/untitled3.png', content: "겹겹이 쌓은 초콜릿 쉬폰케이크 층 사이를 생크림과 체리로 채운 독일을 정통 케이크", kal: 617, sugars: 42, protein: 8, saturated_fat: 19, natrium: 155 },
        { menu: "프리미엄롤케이크", src: './img/menu/untitled.png', content: "생크림 롤케이크에 신선하고 달콤한 각종 과일이 올라간 프리미엄 롤케이크", kal: 320, sugars: 31, protein: 9, saturated_fat: 6, natrium: 80}
    ],
    // 음료 
    [
        { menu: "크림바닐라라떼", src: './img/menu/beverage-tab01-01.png', content: "콜드브루 커피에 바닐라향의 크리미한 우유거품이 올라간 음료", kal: 228, sugars: 0, protein: 10, saturated_fat: 0, natrium: 160 },
        { menu: "말차크림라떼", src: './img/menu/beverage-tab01-02.png', content: "직접 제조한 제주녹차 베이스에 에스프레소가 그라데이션 된 음료", kal: 145, sugars: 17, protein: 4.5, saturated_fat: 3, natrium: 100 },
        { menu: "에스프레소", src: './img/menu/beverage-tab01-06.png', content: "정통방식으로 고압을 이용하여 추출하는 커피, 빵선생의 모든 커피메뉴의 기본", kal: 5, sugars: 0, protein: 0, saturated_fat: 0, natrium: 0 },
        { menu: "아메리카노", src: './img/menu/beverage-tab01-07.png', content: "고소한 향미와 깊고 깔끔한 뒷맛이 특징인 음료", kal: 2, sugars: 0, protein: 0.12, saturated_fat: 0.083, natrium: 13 },
        { menu: "카페라떼", src: './img/menu/beverage-tab01-08.png', content: "진한 에스프레소와 부드러운 우유가 만나 고소한 풍미를 더하는 가장 대중적인 메뉴", kal: 125, sugars: 18, protein: 3.9, saturated_fat: 2.6, natrium: 95 },
        { menu: "카푸치노", src: './img/menu/beverage-tab01-09.png', content: "에스프레소에 부드러운 우유 거품을 풍부하게 올려 시나몬파우더를 첨가해 커피의 풍부함을 즐길 수 있는 음료", kal: 8, sugars: 5, protein: 5, saturated_fat: 5, natrium: 76 },
        { menu: "바닐라라떼", src: './img/menu/beverage-tab01-10.png', content: "부드러운 라떼에 은은한 바닐라 향이 더해져 더욱 달콤하게 즐길 수 있는 음료", kal: 228, sugars: 0, protein: 10, saturated_fat: 0, natrium: 160 },
        { menu: "카페모카", src: './img/menu/beverage-tab01-11.png', content: "모카시럽을 만나 한층 풍부해진 에스프레소에 우유로 부드러움을 더한 음료", kal: 295, sugars: 25, protein: 9, saturated_fat: 3.1, natrium: 130 },
        { menu: "카라멜마끼아또", src: './img/menu/beverage-tab01-12.png', content: "우유 속에 감춰진 카라멜의 달콤함과 에스프레소의 진한 맛이 돋보이는 음료", kal: 190, sugars: 14, protein: 8, saturated_fat: 0, natrium: 230 },
        { menu: "더치아인슈패너", src: './img/menu/beverage-tab01-13.png', content: "쫀쫀하고 부드러운 아인슈패너크림과 더치커피가 어우러진 빵카페 대표 클래식 아인슈패너", kal: 122, sugars: 7.11, protein: 0.72, saturated_fat: 6.199, natrium: 13},
        { menu: "제주녹차라떼", src: './img/menu/beverage-tab2-01.png', content: "직접 제조한 제주녹차 베이스에 부드러운 우유가 어우러진 음료", kal: 75, sugars: 11.61, protein: 2.45, saturated_fat: 1.41, natrium: 30 },
        { menu: "고구마크림라떼", src: './img/menu/beverage-tab01-05.png', content: "꿀고구마의 풍미와 아인슈페너 크림이 어우러진 음료", kal: 115, sugars: 20.42, protein: 2.43, saturated_fat: 1.303, natrium: 34 },
        { menu: "진한초코라떼", src: './img/menu/beverage-tab2-03.png', content: "달콤한 초코와 부드러운 우유가 어우러진 논커피라떼 음료", kal: 90, sugars: 19, protein: 2, saturated_fat: 0, natrium: 60 },
        { menu: "꿀바나나라떼", src: './img/menu/beverage-tab01-03.png', content: "꿀에 절여진 바나나가 생으로 씹히는 달콤한 음료", kal: 135, sugars: 18, protein: 5, saturated_fat: 2.9, natrium: 80 },
        { menu: "크림미숫가루", src: './img/menu/beverage-tab01-04.png', content: "고소한 미숫가루에 달콤하고 부드러운 아인슈페너 크림이 올라간 시그니쳐 음료", kal: 361, sugars: 0.99, protein: 13.65, saturated_fat: 0.491, natrium: 9 },
        { menu: "크라운밀크티", src: './img/menu/beverage-tab2-04.png', content: "빵카페에서 직접 끓여 만드는 수제 밀크티", kal: 290, sugars: 30, protein: 10, saturated_fat: 7, natrium: 190 },
        { menu: "얼그레이", src: './img/menu/beverage-tab2-05.png', content: "향긋하게 풍기는 향과 맛에 두번 반하는 상쾌한 맛의 얼그레이티", kal: 0, sugars: 0, protein: 0, saturated_fat: 0, natrium: 0 },
        { menu: "잉글리쉬블랙퍼스트", src: './img/menu/beverage-tab2-06.png', content: "몰티한 맛의 아쌈과 스모키한 향의 실론캔디를 블렌딩하여 나른한 일상의 휴식이 되어주는 홍차", kal: 5, sugars: 0, protein: 0, saturated_fat: 0, natrium: 15 },
        { menu: "캐모마일티", src: './img/menu/beverage-tab2-07.png', content: "캐모마일의 향긋한 향이 일품인 허브차", kal: 1, sugars: 0, protein: 0, saturated_fat: 0.002, natrium: 1 },
        { menu: "페퍼민트티", src: './img/menu/beverage-tab2-08.png', content: "멘톨향의 강한 청량감, 상쾌한 맛과 향기가 특징인 대표 허브차", kal: 0, sugars: 0, protein: 0, saturated_fat: 0, natrium: 0 },
        { menu: "애플시나몬티", src: './img/menu/beverage-tab01-09.png', content: "사과의 달콤한 향기와 은은하게 퍼지는 시나몬향이 일품인 차", kal: 111, sugars: 19, protein: 1, saturated_fat: 0, natrium: 2 },
        { menu: "유자캐모마일티", src: './img/menu/beverage-tab01-07.png', content: "달콤한 유자과 캐모마일의 향긋한 향이 일품인 허브차", kal: 120, sugars: 27, protein: 0, saturated_fat: 0, natrium: 3 },
        { menu: "자몽얼그레이티", src: './img/menu/beverage-tab3-07.png', content: "직접 착즙한 자몽과 얼그레이가 어우러진 향긋한 생과일 허브차", kal: 20, sugars: 4.43, protein: 0.26, saturated_fat: 0.008, natrium: 2 },
        { menu: "피치블랙티", src: './img/menu/beverage-tab2-12.png', content: "달콤하고 향긋한 복숭아베이스에 홍차가 어우러진 복숭아 홍차 아이스티", kal: 120, sugars: 29, protein: 0, saturated_fat: 0, natrium: 0 },
        { menu: "허니레몬티", src: './img/menu/beverage-tab2-13.png', content: "직접 착즙한 레몬이 들어간 새콤달콤한 과일차", kal: 27, sugars: 6.57, protein: 0.1, saturated_fat: 0, natrium: 2 },
        { menu: "레몬오렌지주스", src: './img/menu/beverage-tab3-06.png', content: "빵카페에서 매일 아침 착즙한 레몬오렌지 생과일 주스", kal: 85, sugars: 18, protein: 0, saturated_fat: 0, natrium: 5 },
        { menu: "루비자몽주스", src: './img/menu/beverage-tab3-07.png', content: "빵카페에서 매일 아침 착즙한 자몽 생과일 주스", kal: 41, sugars: 9.51, protein: 0.52, saturated_fat: 0.015, natrium: 1 },
        { menu: "망고망고주스", src: './img/menu/beverage-tab3-011.png', content: "향긋한 망고향이 매력적인 상큼하고 달콤한 빵카페 인기 생과일 주스", kal: 61, sugars: 15.06, protein: 0.21, saturated_fat: 0.027, natrium: 2 },
        { menu: "블루베리바나나주스", src: './img/menu/untitled1.png', content: "블루베리와 바나나가 통으로 들어가 든든한 생과일 주스", kal: 93, sugars: 12.83, protein: 1.14, saturated_fat: 0.117, natrium: 1 },
        { menu: "리얼레몬에이드", src: './img/menu/untitled(2).png', content: "빵카페에서 매일 아침 착즙한 레몬과 탄산수의 레몬에이드", kal: 100, sugars: 25, protein: 0, saturated_fat: 0, natrium: 10 },
        { menu: "리얼오렌지에이드", src: './img/menu/beverage-tab3-06.png', content: "빵카페에서 매일 아침 착즙한 레몬과 탄산수의 오렌지에이드", kal: 52, sugars: 11.6, protein: 0, saturated_fat: 0.002, natrium: 3 },
        { menu: "리얼자몽에이드", src: './img/menu/beverage-tab3-07.png', content: "빵카페에서 매일 아침 착즙한 레몬과 탄산수의 자몽에이드", kal: 120, sugars: 0, protein: 2.22, saturated_fat: 1, natrium: 0 },
        { menu: "바나바닐라쉐이크", src: './img/menu/beverage-tab3-08.png', content: "바닐라 아이스크림과 바나나를 통으로 갈아만든 바나바닐라 쉐이크", kal: 79, sugars: 11.82, protein: 1.81, saturated_fat: 0.305, natrium: 16 },
        { menu: "블루베리쉐이크", src: './img/menu/beverage-tab3-09.png', content: "바닐라 아이스크림에 달콤하고 상큼한 블루베리를 통으로 갈아만든 블루베리 쉐이크", kal: 228, sugars: 0, protein: 4.2, saturated_fat: 2, natrium: 0 },
        { menu: "스트로베리쉐이크", src: './img/menu/beverage-tab3-10.png', content: "바닐라 아이스크림에 새콤달콤한 딸기를 통으로 갈아만든 딸기 쉐이크", kal: 81, sugars: 11.96, protein: 1.53, saturated_fat: 0.765, natrium: 21 },
        { menu: "제주녹차쉐이크", src: './img/menu/beverage-tab3-11.png', content: "바닐라 아이스크림에 직접 제조한 녹차베이스를 갈아만든 제주녹차 쉐이크", kal: 107, sugars: 7, protein: 15, saturated_fat: 0, natrium: 170 },
        { menu: "진한초콜릿쉐이크", src: './img/menu/beverage-tab3-121.png', content: "바닐라 아이스크림에 달콤하고 진한초코를 갈아만든 초콜릿 쉐이크", kal: 348, sugars: 4.1, protein: 14, saturated_fat: 37, natrium: 0 }
    ], 
    // 디저트&쿠키
    [
        { menu: "계절과일타르트조각(딸기)", src: './img/menu/untitled22.png', content: "두꺼운 크림치즈에 딸기가 가득올라간 타르트 조각 케이크", kal: 335, sugars: 23, protein: 5, saturated_fat: 9, natrium: 75 },
        { menu: "계절과일타르트조각(블루베리)", src: './img/menu/untitled21.png', content: "두꺼운 크림치즈에 블루베리가 가득올라간 타르트 조각 케이크", kal: 335, sugars: 23, protein: 5, saturated_fat: 9, natrium: 75 },
        { menu: "계절과일타르트조각(청포도)", src: './img/menu/untitled20.png', content: "두꺼운 크림치즈에 청포도가 가득올라간 타르트 조각 케이크", kal: 335, sugars: 23, protein: 5, saturated_fat: 9, natrium: 75 },
        { menu: "무스오쇼콜라", src: './img/menu/untitled14.png', content: "진한 다크초콜릿과 부드럽고 폭신한 머랭의 조화가 일품인 프랑스 디저트", kal: 385, sugars: 36, protein: 0, saturated_fat: 15, natrium: 115 },
        { menu: "무화과파운드", src: './img/menu/untitled13.png', content: "부드러운 빵 사이에 쫀득한 무화과가 박혀 있는 촉촉한 무화과 파운드", kal: 350, sugars: 26.78, protein: 5.89, saturated_fat: 3.113, natrium: 258 },
        { menu: "생크림조각케이크(딸기)", src: './img/menu/untitled10.png', content: "동물성 생크림을 사용해 더욱 건강한 딸기 생크림 조각 케이크", kal: 170, sugars: 8, protein: 2.2, saturated_fat: 6, natrium: 45 },
        { menu: "초코생크림조각케이크", src: './img/menu/untitled7.png', content: "건강한 동물성 생크림에 달콤한 가나슈크림이 더해져 부드럽고 달콤한 초코생크림 조각케이크", kal: 287, sugars: 16, protein: 4, saturated_fat: 4.2, natrium: 196 },
        { menu: "티라미수컵", src: './img/menu/11untitled.png', content: "커피, 마스카르포네 치즈 등으로 만든 달콤하고 부드러운 디저트", kal: 344, sugars: 25, protein: 6, saturated_fat: 25, natrium: 166 },
        { menu: "머랭쿠키(블루베리)", src: './img/menu/bread-tab02-05.png', content: "바삭한식감이 매력적인 달콤한 블루베리 머랭쿠키", kal: 79, sugars: 19.3, protein: 1.04, saturated_fat: 0, natrium: 17 },
        { menu: "머랭쿠키(바닐라)", src: './img/menu/bread-tab02-04.png', content: "바삭한식감이 매력적인 달콤한 바닐라 머랭쿠키", kal: 79, sugars: 19.3, protein: 1.04, saturated_fat: 0, natrium: 17 },
        { menu: "머랭쿠키(망고)", src: './img/menu/bread-tab02-03.png', content: "바삭한식감이 매력적인 달콤한 망고 머랭쿠키", kal: 79, sugars: 19.3, protein: 1.04, saturated_fat: 0, natrium: 17 },
        { menu: "머랭쿠키(딸기)", src: './img/menu/bread-tab02-02.png', content: "바삭한식감이 매력적인 달콤한 딸기 머랭쿠키", kal: 79, sugars: 19.3, protein: 1.04, saturated_fat: 0, natrium: 17 },
        { menu: "마카롱", src: './img/menu/bread-tab02-01.png', content: "머랭으로 만든 크러스트 사이에 부드럽고 촉촉한 필링이 어우러진 달콤한 디저트", kal: 150, sugars: 16, protein: 2, saturated_fat: 3.5, natrium: 21 }
    ],
    [
        { menu: "밤파이 6구 10구", src: "./img/menu/1596015249302.jpg", content: "바삭한 페스츄리안에 알밤이 가득한 영양만점 밤파이", kal: "", sugars: "", protein: "", saturated_fat: "", natrium: "" }
    ]
]